/* ###################################################################
**     This component module is generated by Processor Expert. Do not modify it.
**     Filename    : PDB1.c
**     Project     : ProcessorExpert
**     Processor   : MK40DX256ZVLQ10
**     Component   : Init_PDB
**     Version     : Component 01.005, Driver 01.05, CPU db: 3.00.001
**     Compiler    : CodeWarrior ARM C Compiler
**     Date/Time   : 2019-01-13, 21:50, # CodeGen: 117
**     Abstract    :
**          This file implements the PDB (PDB0) module initialization
**          according to the Peripheral Initialization settings, and
**          defines interrupt service routines prototypes.
**     Settings    :
**          Component name                                 : PDB1
**          Device                                         : PDB0
**          Settings                                       : 
**            Clock gate                                   : Enabled
**            Clock settings                               : 
**              Prescaler                                  : divide by 1
**              Divider                                    : divide by 1
**              Counter frequency                          : 20.972 MHz
**              Modulus                                    : 6250
**              Counter period                             : 298.023 us
**              Continuous mode enable                     : Continuous
**              Interrupt delay value                      : 0
**              Interrupt delay                            : 0.000 us
**            Load Mode                                    : Immediate
**          Channels                                       : 
**            Channel triggers                             : 
**              Channel 0 trigger                          : 
**                Trigger A                                : 
**                  Trigger A enable                       : Enabled
**                  Output select A                        : Delay only
**                  Back to Back                           : Disabled
**                  Trigger delay A value                  : 0
**                  Trigger A delay                        : 0.000 us
**                Trigger B                                : 
**                  Trigger B enable                       : Disabled
**                  Output select B                        : bypassed
**                  Back to Back                           : Disabled
**                  Trigger delay B value                  : 0
**                  Trigger B delay                        : 0.000 us
**              Channel 1 trigger                          : 
**                Trigger A                                : 
**                  Trigger A enable                       : Disabled
**                  Output select A                        : Delay only
**                  Back to Back                           : Disabled
**                  Trigger delay A value                  : 0
**                  Trigger A delay                        : 0.000 us
**                Trigger B                                : 
**                  Trigger B enable                       : Disabled
**                  Output select B                        : bypassed
**                  Back to Back                           : Disabled
**                  Trigger delay B value                  : 0
**                  Trigger B delay                        : 0.000 us
**            Channel for DAC                              : 
**              Trigger to DAC0                            : 
**                Trigger Output                           : Disabled
**                External trigger input enable            : Disabled
**                Trigger interval value                   : 0
**                Trigger interval time                    : 0.048 us
**              Trigger to DAC1                            : 
**                Trigger Output                           : Disabled
**                External trigger input enable            : Disabled
**                Trigger interval value                   : 0
**                Trigger interval time                    : 0.048 us
**            Pulse outs                                   : 
**              Pulse out 0                                : 
**                Pulse output                             : Disabled
**                Delay 1 value                            : 0
**                Delay of rising edge                     : 0.000 us
**                Delay 2 value                            : 0
**                Delay of falling edge                    : 0.000 us
**          Pins/Signals                                   : 
**            Input trigger pin allocation                 : Enabled
**              Input trigger select                       : PDB_SWTRIG
**              Input trigger select signal                : 
**          Interrupts/DMA                                 : 
**            Interrupt                                    : INT_PDB0
**            Interrupt request                            : Disabled
**            Interrupt priority                           : 0 (Highest)
**            ISR name                                     : PDBinterrupt
**            PDB interrupt                                : Disabled
**            Sequence error interrupt                     : Enabled
**            DMA request                                  : Disabled
**          Initialization                                 : 
**            Load OK                                      : yes
**            Enable PDB                                   : yes
**            Call Init method                             : no
**     Contents    :
**         Init - void PDB1_Init(void);
**
**     Copyright : 1997 - 2014 Freescale Semiconductor, Inc. 
**     All Rights Reserved.
**     
**     Redistribution and use in source and binary forms, with or without modification,
**     are permitted provided that the following conditions are met:
**     
**     o Redistributions of source code must retain the above copyright notice, this list
**       of conditions and the following disclaimer.
**     
**     o Redistributions in binary form must reproduce the above copyright notice, this
**       list of conditions and the following disclaimer in the documentation and/or
**       other materials provided with the distribution.
**     
**     o Neither the name of Freescale Semiconductor, Inc. nor the names of its
**       contributors may be used to endorse or promote products derived from this
**       software without specific prior written permission.
**     
**     THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
**     ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
**     WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
**     DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR
**     ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
**     (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
**     LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON
**     ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
**     (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
**     SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
**     
**     http: www.freescale.com
**     mail: support@freescale.com
** ###################################################################*/
/*!
** @file PDB1.c
** @version 01.05
** @brief
**          This file implements the PDB (PDB0) module initialization
**          according to the Peripheral Initialization settings, and
**          defines interrupt service routines prototypes.
*/         
/*!
**  @addtogroup PDB1_module PDB1 module documentation
**  @{
*/         

/* MODULE PDB1. */

#include "PDB1.h"
  /* Including shared modules, which are used in the whole project */
#include "PE_Types.h"
#include "PE_Error.h"
#include "PE_Const.h"
#include "IO_Map.h"
#include "Cpu.h"


/*
** ===================================================================
**     Method      :  PDB1_Init (component Init_PDB)
**     Description :
**         This method initializes registers of the PDB module
**         according to the Peripheral Initialization settings.
**         Call this method in user code to initialize the module. By
**         default, the method is called by PE automatically; see "Call
**         Init method" property of the component for more details.
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/
void PDB1_Init(void)
{
  /* SIM_SCGC6: PDB=1 */
  SIM_SCGC6 |= SIM_SCGC6_PDB_MASK;
  /* PDB0_SC: ??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,LDMOD=0,PDBEIE=1,SWTRIG=0,DMAEN=0,PRESCALER=0,TRGSEL=0x0F,PDBEN=0,PDBIF=0,PDBIE=0,??=0,MULT=0,CONT=1,LDOK=0 */
  PDB0_SC = PDB_SC_LDMOD(0x00) |
            PDB_SC_PDBEIE_MASK |
            PDB_SC_PRESCALER(0x00) |
            PDB_SC_TRGSEL(0x0F) |
            PDB_SC_MULT(0x00) |
            PDB_SC_CONT_MASK;
  /* PDB0_MOD: ??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,MOD=0x186A */
  PDB0_MOD = PDB_MOD_MOD(0x186A);
  /* PDB0_IDLY: ??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,IDLY=0 */
  PDB0_IDLY = PDB_IDLY_IDLY(0x00);
  /* PDB0_CH0C1: BB&=~3,TOS&=~2,TOS|=1,EN&=~2,EN|=1 */
  PDB0_CH0C1 = (uint32_t)((PDB0_CH0C1 & (uint32_t)~(uint32_t)(
                PDB_C1_BB(0x03) |
                PDB_C1_TOS(0x02) |
                PDB_C1_EN(0x02)
               )) | (uint32_t)(
                PDB_C1_TOS(0x01) |
                PDB_C1_EN(0x01)
               ));
  /* PDB0_CH0S: ??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,CF=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,ERR=0xFF */
  PDB0_CH0S = (PDB_S_CF(0x00) | PDB_S_ERR(0xFF));
  /* PDB0_CH0DLY0: DLY=0 */
  PDB0_CH0DLY0 &= (uint32_t)~(uint32_t)(PDB_DLY_DLY(0xFFFF));
  /* PDB0_CH0DLY1: DLY=0 */
  PDB0_CH0DLY1 &= (uint32_t)~(uint32_t)(PDB_DLY_DLY(0xFFFF));
  /* PDB0_CH1C1: BB&=~3,TOS&=~2,TOS|=1,EN&=~3 */
  PDB0_CH1C1 = (uint32_t)((PDB0_CH1C1 & (uint32_t)~(uint32_t)(
                PDB_C1_BB(0x03) |
                PDB_C1_TOS(0x02) |
                PDB_C1_EN(0x03)
               )) | (uint32_t)(
                PDB_C1_TOS(0x01)
               ));
  /* PDB0_CH1S: ??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,CF=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,ERR=0xFF */
  PDB0_CH1S = (PDB_S_CF(0x00) | PDB_S_ERR(0xFF));
  /* PDB0_CH1DLY0: DLY=0 */
  PDB0_CH1DLY0 &= (uint32_t)~(uint32_t)(PDB_DLY_DLY(0xFFFF));
  /* PDB0_CH1DLY1: DLY=0 */
  PDB0_CH1DLY1 &= (uint32_t)~(uint32_t)(PDB_DLY_DLY(0xFFFF));
  /* PDB0_DACINT0: ??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,INT=0 */
  PDB0_DACINT0 = PDB_INT_INT(0x00);
  /* PDB0_DACINT1: ??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,INT=0 */
  PDB0_DACINT1 = PDB_INT_INT(0x00);
  /* PDB0_DACINTC0: ??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,EXT=0,TOE=0 */
  PDB0_DACINTC0 = 0x00U;
  /* PDB0_DACINTC1: ??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,EXT=0,TOE=0 */
  PDB0_DACINTC1 = 0x00U;
  /* PDB0_PO0DLY: DLY1=0,DLY2=0 */
  PDB0_PO0DLY = (PDB_PODLY_DLY1(0x00) | PDB_PODLY_DLY2(0x00));
  /* PDB0_POEN: POEN&=~1 */
  PDB0_POEN &= (uint32_t)~(uint32_t)(PDB_POEN_POEN(0x01));
  /* PDB0_SC: PDBEN=1,LDOK=1 */
  PDB0_SC |= (PDB_SC_PDBEN_MASK | PDB_SC_LDOK_MASK);
}

/*
** ###################################################################
**
**  The interrupt service routine(s) must be implemented
**  by user in one of the following user modules.
**
**  If the "Generate ISR" option is enabled, Processor Expert generates
**  ISR templates in the CPU event module.
**
**  User modules:
**      ProcessorExpert.c
**      Events.c
**
** ###################################################################
PE_ISR(PDBinterrupt)
{
// NOTE: The routine should include actions to clear the appropriate
//       interrupt flags.
//
}
*/


/* END PDB1. */
/*!
** @}
*/
/*
** ###################################################################
**
**     This file was created by Processor Expert 10.3 [05.09]
**     for the Freescale Kinetis series of microcontrollers.
**
** ###################################################################
*/
